name: CI with SonarQube

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Generate .env file
        run: |
          echo "VITE__ADMIN_PORTAL__APP_ENV=local" >> ./apps/admin-portal/.env
          echo "VITE__ADMIN_PORTAL__API_ENDPOINT=http://192.168.152.39:7291" >> ./apps/admin-portal/.env
          echo "VITE__ADMIN_PORTAL__REACT_QUERY_DEBUGGING=false" >> ./apps/admin-portal/.env

          echo "VITE__USER_PORTAL__APP_ENV=local" >> ./apps/user-portal/.env
          echo "VITE__USER_PORTAL__API_ENDPOINT=http://192.168.152.39:7291" >> ./apps/user-portal/.env
          echo "VITE__USER_PORTAL__REACT_QUERY_DEBUGGING=false" >> ./apps/user-portal/.env

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=frontend-app \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://sonar.itechind.com:9000 \
            -Dsonar.login=$SONAR_TOKEN
